import { ITeacherProfileInterviewDay } from "./iteacher-profile-interview-day";
import { ITeacherProfileLanguage } from "./iteacher-profile-language";
import { ITeacherProfileProgram } from "./iteacher-profile-program";
import { ITeacherProfileRewayat } from "./iteacher-profile-rewayat";

export interface ITeacherProfile {
    fnameAr?: string;
    mnameAr?: string;
    fanameAr?: string;
    fnameEn?: string;
    mnameEn?: string;
    faNameEn?: string;
    gender?: string;
    mobile?: string;
    gregBirthDate?: string;
    hijriBirthDate?: string;
    nationality?: string;
    nationalityAr?: string;
    nationalityEn?: string;
    country?: string;
    countryAr?: string;
    countryEn?: string;
    city?: string;
    cityAr?: string;
    cityEn?: string;
    interviewDay?: string;
    interviewTime?: string;
    acEdu?: string;
    qualifi?: string;
    qualifiAr?: string;
    qualifiEn?: string;
    specia?: string;
    speciaAr?: string;
    speciaEn?: string;
    agency?: string;
    eduYear?: string;
    eduYearAr?: string;
    eduYearEn?: string;
    entity?: string;
    isHasQuranExp?: boolean;
    isHasTeachSunnaExp?: boolean;
    isHasInternetTeachExp?: boolean;
    isHasTeachForeignerExp?: boolean;
    isHasEjazaHafz?: boolean;
    isHasEjazaTelawa?: boolean;
    anyLangReading?: string;
    lang?: string;
    langAr?: string;
    langEn?: string;
    workingPlatForm?: string;
    workingPlatFormAr?: string;
    workingPlatFormEn?: string;
    degree?: string;
    degreeAr?: string;
    degreeEn?: string;
    bankName?: string;
    bankNumber?: string;
    from?: string;
    to?: string;
    usrName?: string; 
    usrEmail?: string;
    proPic?: string;
    teacherPrograms?: ITeacherProfileProgram[];
    interviewDays?:ITeacherProfileInterviewDay[];
    rewayats?:ITeacherProfileRewayat[];
    Languages?:ITeacherProfileLanguage[];
}
