
import { ITeacherProfileInterviewDayLookup } from "./iteacher-profile-interview-day-lookup";
import { ITeacherProfileLookup } from "./iteacher-profile-lookup";

export interface ITeacherProfile{
    
    fnameAr?:string;
    mnameAr?:string;
    fanameAr?:string;
    fnameEn?:string;
    mnameEn?:string;
    faNameEn?:string;
    gender?:string;
    mobile?:string;
    address?:string;
    gregBirthDate?:string;
    hijriBirthDate?:string;
    nationality?:string;
    nationalityAr?:string;
    nationalityEn?:string;
    country?:string;
    countryAr?:string;
    countryEn?:string;
    city?:string;
    cityAr?:string;
    cityEn?:string;
    eduLevel?:string;
    educationLevelAr?:string;
    educationLevelEn?:string;
    qualifi?:string;
    qualifiAr?:string;
    qualifiEn?:string;
    specia?:string;
    speciaAr?:string;
    speciaEn?:string;
    eduYear?:string;
    eduYearAr?:string;
    eduYearEn?:string;
    entity?:string;
    isHasQuranExp?:boolean;
    isHasTeachSunnaExp?:boolean;
    isHasInternetTeachExp?:boolean;
    isHasTeachForeignerExp?:boolean;
    isHasEjazaHafz?:boolean;
    isHasEjazaTelawa?:boolean;
    agency?:string;
    agencyAr?:string;
    agencyEn?:string;
    workingPlatForm?:string;
    workingPlatFormAr?:string;
    workingPlatFormEn?:string;
    degree?:string;
    degreeAr?:string;
    degreeEn?:string;
    bankName?:string;
    bankNumber?:string;
    usrName?:string;
    usrEmail?:string;
    proPic?:string;
    ejazaAttachments?:[];
    teacherPrograms ?: ITeacherProfileLookup[];
    interviewDays ?: ITeacherProfileInterviewDayLookup[];
    rewayats ?: ITeacherProfileLookup[];
    languages ?: ITeacherProfileLookup[];
}
