
import { IAttachment } from "../attachments-interfaces/iattachment";
import { ITeacherProfileAvailabilityLookup } from "./iteacher-availability-lookup";
import { ITeacherProfileLookup } from "./iteacher-profile-lookup";
import { ITeacherProfileProgramDegreeLookup } from "./iteacher-profile-program-lookup";

export interface ITeacherProfile{

    fnameAr?:string;
    mnameAr?:string;
    fanameAr?:string;
    fnameEn?:string;
    mnameEn?:string;
    faNameEn?:string;
    gender?:string;
    mobile?:string;
    address?:string;
    gregBirthDate?:string;
    hijriBirthDate?:string;
    nationality?:string;
    arbNatName?:string;
    engNatName?:string;
    country?:string;
    countryAr?:string;
    countryEn?:string;
    city?:string;
    cityAr?:string;
    cityEn?:string;
    eduLevel?:string;
    educationLevelAr?:string;
    educationLevelEn?:string;
    qualifi?:string;
    qualifiAr?:string;
    qualifiEn?:string;
    specia?:string;
    speciaAr?:string;
    speciaEn?:string;
    eduDate?: string;
    eduUnitAr?:string;
    eduUnitEn?:string;
    eduNum?: number;
    entity?:string;
    isHasQuranExp?:boolean;
    isHasTeachSunnaExp?:boolean;
    isHasInternetTeachExp?:boolean;
    isHasTeachForeignerExp?:boolean;
    isHasEjazaHafz?:boolean;
    isHasEjazaTelawa?:boolean;
    agency?:string;
    agencyAr?:string;
    agencyEn?:string;
    workingPlatForm?:string;
    workingPlatFormAr?:string;
    workingPlatFormEn?:string;
    interviewHijri?:string;
    interviewAr?:string;
    interviewEn?:string;
    interviewTime?:string;
    bankName?:string;
    bankNumber?:string;
    usrName?:string;
    usrEmail?:string;
    proPic?:string;
    ejazaAttachments?:IAttachment[];
    teacherPrograms ?: ITeacherProfileProgramDegreeLookup[];
    availabilityDays ?: ITeacherProfileAvailabilityLookup[];
    rewayats ?: ITeacherProfileLookup[];
    languages ?: ITeacherProfileLookup[];
    birthGregorian?:string;
    birthDispMode?:number;
}
