export enum LookupsEnum {
    GENDER = "GENDER",
    CONTENT_MANAG_TYPE = "CONTENT_MANAG_TYPE",
    EDU_LEVEL ="EDU_LEVEL",
    MEDIA_TYPES = "MEDIA_TYPES",
    SOC_MED_TYPES = "SOC_MED_TYPES",
    MATERIAL_CATEG = "MATERIAL_CATEG",
    NATIONALITY = "NATIONALITY",
    COUNTRY = "COUNTRY"
}

